/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Modelo.modeloGrex.*;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Bryantcore
 */
public class ConsultarPlantilla extends javax.swing.JFrame {
          
    /**
     * Creates new form ConsultarPlantilla
     */
    public ConsultarPlantilla() {
        initComponents();
        setExtendedState(java.awt.Frame.MAXIMIZED_BOTH);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        botonAgregar = new javax.swing.JButton();
        campoRango = new javax.swing.JTextField();
        campoSalario = new javax.swing.JTextField();
        campoCelular = new javax.swing.JTextField();
        campoCorreo = new javax.swing.JTextField();
        campoFechaContratacion = new javax.swing.JTextField();
        campoID = new javax.swing.JTextField();
        campoPrimerNombre = new javax.swing.JTextField();
        campoSegundoNombre = new javax.swing.JTextField();
        campoPrimerApellido = new javax.swing.JTextField();
        campoSegundoApellido = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        botonBuscar = new javax.swing.JButton();
        botonBorrar = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        botonLimpiar = new javax.swing.JButton();
        CampoSexo = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        CampoEnlaceCV = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        campoObservaciones = new javax.swing.JTextField();
        botonActualizar = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        JTblTablaTodos2 = new javax.swing.JTable();
        botonMostrarTodosTrabajadores = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Gestión"));

        jLabel2.setText("*Para crear un nuevo registro, ingrese los datos (consulte a su empresa qué datos no son obligatorios).");

        jLabel3.setText("ID:");

        jLabel1.setText("Primer nombre:");

        jLabel4.setText("Segundo nombre:");

        jLabel5.setText("Primer apellido:");

        jLabel6.setText("Segundo apellido:");

        jLabel7.setText("Sexo:");

        jLabel8.setText("Rango:");

        jLabel9.setText("Salario:");

        jLabel10.setText("Celular (omita el primer cero):");

        jLabel11.setText("Correo:");

        jLabel12.setText("Fecha de contratación:");

        botonAgregar.setText("Agregar");
        botonAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAgregarActionPerformed(evt);
            }
        });

        campoRango.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoRangoActionPerformed(evt);
            }
        });

        jLabel13.setText("*Para buscar un registro, solo debe ingresar el ID del empleado.");

        botonBuscar.setText("Buscar");
        botonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBuscarActionPerformed(evt);
            }
        });

        botonBorrar.setText("Borrar");
        botonBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBorrarActionPerformed(evt);
            }
        });

        jLabel14.setText("*Para actualizar un registro, ingrese el ID correspondiente y los nuevos datos.");

        jLabel15.setText("*Para eliminar un registro, solo debe ingresar el ID correspondiente.");

        botonLimpiar.setText("Limpiar campos");
        botonLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonLimpiarActionPerformed(evt);
            }
        });

        CampoSexo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampoSexoActionPerformed(evt);
            }
        });

        jLabel17.setText("Enlace al CV:");

        jLabel16.setText("Observaciones:");

        campoObservaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoObservacionesActionPerformed(evt);
            }
        });

        botonActualizar.setText("Actualizar");
        botonActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonActualizarActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14)
                    .addComponent(jLabel15)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(botonBorrar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(botonAgregar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel1)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel11)
                            .addComponent(jLabel17)
                            .addComponent(jLabel12)
                            .addComponent(jLabel16))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CampoEnlaceCV)
                            .addComponent(campoPrimerNombre)
                            .addComponent(campoSegundoNombre)
                            .addComponent(campoPrimerApellido)
                            .addComponent(campoSegundoApellido)
                            .addComponent(campoRango)
                            .addComponent(campoSalario)
                            .addComponent(campoCelular)
                            .addComponent(CampoSexo, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(campoCorreo, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(campoFechaContratacion)
                            .addComponent(campoObservaciones)
                            .addComponent(campoID)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(botonLimpiar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE)
                                    .addComponent(botonBuscar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(botonActualizar, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE)))))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(campoID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(campoPrimerNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(campoSegundoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(campoPrimerApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(campoSegundoApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(CampoSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(campoRango, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(campoSalario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(campoObservaciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(campoCelular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(campoCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(CampoEnlaceCV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(campoFechaContratacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonAgregar)
                    .addComponent(botonBuscar)
                    .addComponent(botonActualizar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botonLimpiar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonBorrar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(153, 153, 153))
        );

        JTblTablaTodos2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Primer nombre", "Segundo nombre", "Primer apellido", "Segundo apellido", "Sexo", "Rango", "Salario", "Observaciones", "Celular", "Correo", "Enlace al CV", "Fecha de contratación"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, true, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(JTblTablaTodos2);

        botonMostrarTodosTrabajadores.setText("Listar toda la nómina de empleados");
        botonMostrarTodosTrabajadores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonMostrarTodosTrabajadoresActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 580, Short.MAX_VALUE)
                    .addComponent(botonMostrarTodosTrabajadores, javax.swing.GroupLayout.DEFAULT_SIZE, 580, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 519, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(botonMostrarTodosTrabajadores)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2))))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void campoObservacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoObservacionesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoObservacionesActionPerformed

    private void CampoSexoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampoSexoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CampoSexoActionPerformed

    private void botonLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonLimpiarActionPerformed
        // TODO add your handling code here:
        campoID.setText("");
        campoPrimerNombre.setText("");
        campoSegundoNombre.setText("");
        campoPrimerApellido.setText("");
        campoSegundoApellido.setText("");
        CampoSexo.setText("");
        campoRango.setText("");
        campoSalario.setText("");
        campoObservaciones.setText("");
        campoCelular.setText("");
        campoCorreo.setText("");
        CampoEnlaceCV.setText("");
        campoFechaContratacion.setText(""); 
    }//GEN-LAST:event_botonLimpiarActionPerformed

    private void botonBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBorrarActionPerformed
        // TODO add your handling code here:
        String id=campoID.getText();
        
        String sentenciaEliminar="delete from Trabajadores where IdTrabajadores="+id;
        
        Modelo.modeloGrex.conectarABDSilencioso();
        
        try{
            Statement st=Modelo.modeloGrex.conexion.createStatement();
            int confirmarEliminar=JOptionPane.showConfirmDialog(null, "¿Está seguro qde ue desea eliminar el registro del empleado con ID "+id+"?", "Confirmar eliminación",JOptionPane.YES_NO_OPTION);
            if (confirmarEliminar==JOptionPane.YES_OPTION){
                st.executeUpdate(sentenciaEliminar);
            }
        }catch(SQLException ex){
            JOptionPane.showMessageDialog(null, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_botonBorrarActionPerformed

    private void botonActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonActualizarActionPerformed
        String id=campoID.getText();
        String primerNombre=campoPrimerNombre.getText();
        String segundoNombre=campoSegundoNombre.getText();
        String primerApellido=campoPrimerApellido.getText();
        String segundoApellido=campoSegundoApellido.getText();
        String sexo=CampoSexo.getText();
        String rango=campoRango.getText();
        String observaciones=campoObservaciones.getText();
        String salario=campoSalario.getText();
        String celular=campoCelular.getText();
        String correo=campoCorreo.getText();
        String enlaceCV=CampoEnlaceCV.getText();
        String fechaContratacion=campoFechaContratacion.getText();
        
        String sentenciaActualizar="update Trabajadores set IdTrabajadores="+id+",PrimerNombre='"+primerNombre+"',SegundoNombre='"+segundoNombre+"',PrimerApellido='"+primerApellido+"',SegundoApellido='"+segundoApellido+"',Sexo='"+sexo+"',Rango='"+rango+"',Salario='";
                Modelo.modeloGrex.conectarABDSilencioso();
    }//GEN-LAST:event_botonActualizarActionPerformed

    private void botonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBuscarActionPerformed
        // TODO add your handling code here:
        String id=campoID.getText();

        String sentenciaBuscar="select * from Trabajadores where IdTrabajadores="+id;

        Modelo.modeloGrex.conectarABDSilencioso();
        try{
            Statement st=Modelo.modeloGrex.conexion.createStatement();
            ResultSet rs=st.executeQuery(sentenciaBuscar);
            if(rs.next()){
                campoPrimerNombre.setText(rs.getString("PrimerNombre"));
                campoSegundoNombre.setText(rs.getString("SegundoNombre"));
                campoPrimerApellido.setText(rs.getString("PrimerApellido"));
                campoSegundoApellido.setText(rs.getString("SegundoApellido"));
                CampoSexo.setText(rs.getString("Sexo"));
                campoRango.setText(rs.getString("Rango"));
                campoSalario.setText(rs.getString("Salario"));
                campoCelular.setText(rs.getString("Celular"));
                campoCorreo.setText(rs.getString("Correo"));
                CampoEnlaceCV.setText(rs.getString("EnlaceCV"));
                campoFechaContratacion.setText(rs.getString("FechaContratacion"));
            } else {
                campoID.setText(rs.getString(""));
            }
        }catch(SQLException ex){
            JOptionPane.showMessageDialog(null, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_botonBuscarActionPerformed

    private void botonMostrarTodosTrabajadoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonMostrarTodosTrabajadoresActionPerformed
        // TODO add your handling code here:
        DefaultTableModel md=new DefaultTableModel();
        ResultSet rs = null;
        try {
            rs = ConsultarPlantilla.ListarTabla("select * from Trabajadores");
        } catch (SQLException ex) {
            Logger.getLogger(ConsultarPlantilla.class.getName()).log(Level.SEVERE, null, ex);
        }
        md.setColumnIdentifiers(new Object[]{"ID","Primer nombre","Segundo nombre",
            "Primer apellido","Segundo apellido","Sexo",
            "Rango","Salario (en USD)",
            "Observaciones","Celular","Correo",
            "Enlace al CV,","Fecha de contratación"});
        try{
            while(rs.next()){
                md.addRow(new Object[]{rs.getInt("IdTrabajadores"),
                    rs.getString("PrimerNombre"),
                    rs.getString("SegundoNombre"),
                    rs.getString("PrimerApellido"),
                    rs.getString("SegundoApellido"),
                    rs.getString("Sexo"),
                    rs.getString("Rango"),
                    rs.getInt("Salario"),
                    rs.getString("Observaciones"),
                    rs.getString("Celular"),
                    rs.getString("Correo"),
                    rs.getString("EnlaceCV"),
                    rs.getString("FechaContratacion")});
                    
            JTblTablaTodos2.setModel(md);
        }
        }catch (Exception e){
            System.out.println(e);
        }
    }//GEN-LAST:event_botonMostrarTodosTrabajadoresActionPerformed

    private void campoRangoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoRangoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoRangoActionPerformed

    private void botonAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAgregarActionPerformed
        // TODO add your handling code here:
        String id=campoID.getText();
        String primerNombre=campoPrimerNombre.getText();
        String segundoNombre=campoSegundoNombre.getText();
        String primerApellido=campoPrimerApellido.getText();
        String segundoApellido=campoSegundoApellido.getText();
        String sexo=CampoSexo.getText();
        String rango=campoRango.getText();
        String observaciones=campoObservaciones.getText();
        String salario=campoSalario.getText();
        String celular=campoCelular.getText();
        String correo=campoCorreo.getText();
        String enlaceCV=CampoEnlaceCV.getText();
        String fechaContratacion=campoFechaContratacion.getText();
        
        String sentenciaInsertar="insert into Trabajadores (IdTrabajadores,PrimerNombre,SegundoNombre,"
                + "PrimerApellido,SegundoApellido,Sexo,"
                + "Rango,Observaciones, Salario,"
                + "Celular,Correo,EnlaceCV,FechaContratacion) values ("+id+",'"+primerNombre+"','"+segundoNombre+"','"
                +primerApellido+"','"+segundoApellido+"','"+sexo+"','"
                +rango+"','"+observaciones+"',"+salario+","
                +celular+",'"+correo+"','"+enlaceCV+"','"+fechaContratacion+"');";
                Modelo.modeloGrex.conectarABDSilencioso();
                try {
                    int confirmarAgregar=JOptionPane.showConfirmDialog(null, "¿Está seguro de que desea agregar este registro?", "Confirmar nuevo registro",JOptionPane.YES_NO_OPTION);
                    if (confirmarAgregar==JOptionPane.YES_OPTION){
                        Statement st = Modelo.modeloGrex.conexion.createStatement();
                        st.executeUpdate(sentenciaInsertar);
                    }
                } catch (SQLException ex) {
                    JOptionPane.showMessageDialog(null, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
                }
    }//GEN-LAST:event_botonAgregarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConsultarPlantilla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConsultarPlantilla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConsultarPlantilla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConsultarPlantilla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConsultarPlantilla().setVisible(true);
            }
        });
    }
    
    public static ResultSet ListarTabla(String consulta) throws SQLException{
        Connection conexion=DriverManager.getConnection("jdbc:mysql://68.64.164.116:19905/db_pa61_bescalante","bescalante","Bescalante78.");
        Statement sql;
        ResultSet datos=null;
        try{
            sql=conexion.createStatement();
            datos=sql.executeQuery(consulta);
        } catch (Exception e){
            System.out.println(e);
        }
        return datos;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CampoEnlaceCV;
    private javax.swing.JTextField CampoSexo;
    private javax.swing.JTable JTblTablaTodos2;
    private javax.swing.JButton botonActualizar;
    private javax.swing.JButton botonAgregar;
    private javax.swing.JButton botonBorrar;
    private javax.swing.JButton botonBuscar;
    private javax.swing.JButton botonLimpiar;
    private javax.swing.JButton botonMostrarTodosTrabajadores;
    private javax.swing.JTextField campoCelular;
    private javax.swing.JTextField campoCorreo;
    private javax.swing.JTextField campoFechaContratacion;
    private javax.swing.JTextField campoID;
    private javax.swing.JTextField campoObservaciones;
    private javax.swing.JTextField campoPrimerApellido;
    private javax.swing.JTextField campoPrimerNombre;
    private javax.swing.JTextField campoRango;
    private javax.swing.JTextField campoSalario;
    private javax.swing.JTextField campoSegundoApellido;
    private javax.swing.JTextField campoSegundoNombre;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
