/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JOptionPane;
import java.sql.*;
import Modelo.*;
import javax.swing.JFrame;

/**
 *
 * @author Bryantcore
 */
public class PantallaPrincipal extends javax.swing.JFrame {
    
    Connection conexion;
    
    public static void java() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    /**
     * Creates new form PantallaPrincipal
     */
    public PantallaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTxtFldCampoUsuario = new javax.swing.JTextField();
        jBttnBotonAcceder = new javax.swing.JButton();
        jLblCerditos = new javax.swing.JLabel();
        jLblTitulo1 = new javax.swing.JLabel();
        jPsswrdFldCampoClave = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Grex: Gestión de la nónima");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jTxtFldCampoUsuario.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTxtFldCampoUsuario.setToolTipText("Usuario");
        jTxtFldCampoUsuario.setAutoscrolls(false);
        jTxtFldCampoUsuario.setName(""); // NOI18N
        jTxtFldCampoUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtFldCampoUsuarioActionPerformed(evt);
            }
        });

        jBttnBotonAcceder.setText("Acceder");
        jBttnBotonAcceder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBttnBotonAccederActionPerformed(evt);
            }
        });

        jLblCerditos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLblCerditos.setText("Grex, por Aprova2 (2024)");

        jLblTitulo1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLblTitulo1.setText("Acceso a la gestión de la nómina");

        jPsswrdFldCampoClave.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel1.setText("Usuario:");

        jLabel2.setText("Clave:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLblCerditos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBttnBotonAcceder, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLblTitulo1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 288, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTxtFldCampoUsuario)
                            .addComponent(jPsswrdFldCampoClave))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLblTitulo1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxtFldCampoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jPsswrdFldCampoClave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBttnBotonAcceder)
                .addGap(23, 23, 23)
                .addComponent(jLblCerditos)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    
    
    private void jBttnBotonAccederActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBttnBotonAccederActionPerformed
        String campoUsuario=jTxtFldCampoUsuario.getText();
        String campoClave=jPsswrdFldCampoClave.getText();
        
        if (campoUsuario.equals("")&&campoClave.equals("")){
            JOptionPane.showMessageDialog(null, "Acceso exitoso.", "Acceso exitoso",JOptionPane.INFORMATION_MESSAGE);
            new GestionEmpleados().setVisible(true); //Muestra MenuPrincipal
            this.setVisible(false); //Oculta PantallaPrincipal
            
            Modelo.modeloGrex.conectarABD();
            
            
            
            } else {
            JOptionPane.showMessageDialog(null, "Datos de ingreso incorrectos. Vuelve a intentarlo.", "Error de acceso", JOptionPane.ERROR_MESSAGE);
            jPsswrdFldCampoClave.setText("");
        }
            
    }//GEN-LAST:event_jBttnBotonAccederActionPerformed

    private void jTxtFldCampoUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtFldCampoUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtFldCampoUsuarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PantallaPrincipal().setVisible(true);
                           }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBttnBotonAcceder;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLblCerditos;
    private javax.swing.JLabel jLblTitulo1;
    private javax.swing.JPasswordField jPsswrdFldCampoClave;
    private javax.swing.JTextField jTxtFldCampoUsuario;
    // End of variables declaration//GEN-END:variables
}
